const countryList = {
    AED: "AE-United Arab Emirates Dirham",
    AFN: "AF-Afghan Afghani",
    XCD: "AG-East Caribbean Dollar",
    AMD: "AM-Armenian Dram",
    ANG: "AN-Netherlands Antillean Guilder ",
    ARS: "AR-Argentine Peso",
    AUD: "AU-Australian Dollar",
    AZN: "AZ-Azerbaijani Manat",
    BBD: "BB-Bahraini Dinar",
    BDT: "BD-Bangladeshi Taka",
    BGN: "BG-Bulgarian Lev",
    BHD: "BH-Bahraini Dinar",
    BND: "BN-Brunei Dollar",
    BRL: "BR-Brazilian Real",
    BSD: "BS-Bahamian Dollar",
    NOK: "BV-Norwegian Krone",
    BYR: "BY-Belarusian Ruble",
    CAD: "CA-Canadian Dollar",
    CHF: "CH-Swiss Franc",
    COP: "CO-Colombian Peso",
    CRC: "CR-Costa Rican Colón",
    CUP: "CU-Cuban Peso",
    CYP: "CY-Euro",
    CZK: "CZ-Czech Koruna",
    DJF: "DJ-Djiboutian Franc",
    DKK: "DK-Danish Krone",
    DOP: "DO-Dominican Peso",
    EUR: "FR-Euro",
    FJD: "FJ-Fijian Dollar",
    GBP: "GB-Pound sterling",
    GEL: "GE-Georgian Lari",
    GIP: "GI-Gibraltar pound",
    GYD: "GY-Guyanese dollar",
    HKD: "HK-Hong Kong Dollar",
    IDR: "ID-Indonesian Rupiah",
    ILS: "IL-sraeli New Shekel",
    INR: "IN-Indian rupee",
    IQD: "IQ-Iraqi Dinar",
    IRR: "IR-Iranian Rial ",
    JMD: "JM-Jamaican Dollar",
    JOD: "JO-Jordanian Dinar",
    JPY: "JP-Japanese Yen",
    KES: "KE-Kenyan Shilling",
    KGS: "KG-Kyrgystani Som",
    KHR: "KH-Cambodian riel",
    KMF: "KM-Comorian Franc",
    KRW: "KR-South Korean won",
    KWD: "KW-Kuwaiti Dinar",
    KYD: "KY-Cayman Islands Dollar",
    KZT: "KZ-Kazakhstani Tenge",
    LBP: "LB-Lebanese pound",
    LKR: "LK-Sri Lankan Rupee",
    LRD: "LR-Liberian Dollar",
    LYD: "LY-Libyan Dinar",
    MAD: "MA-Moroccan Dirham",
    MGA: "MG-Malagasy Ariary",
    MMK: "MM-Myanmar Kyat",
    MXN: "MX-Mexican Peso",
    MYR: "MY-Malaysian ringgit ",
    NGN: "NG-Nigerian Naira",
    NZD: "NZ-New Zealand dollar",
    OMR: "OM-Omani Rial",
    PAB: "PA-Panamanian Balboa",
    PHP: "PH-Philippine peso",
    PKR: "PK-Pakistani Rupee",
    QAR: "QA-Qatari Riyal",
    RON: "RO-Romanian Leu",
    RSD: "RS-Serbian Dinar",
    RUB: "RU-Russian Ruble",
    SAR: "SA-Saudi riyal",
    SBD: "SB-Solomon Islands Dollar",
    SEK: "SE-Swedish Krona",
    SGD: "SG-Singapore Dolla",
    SOS: "SO-Somali Shilling",
    SRD: "SR-Suriname Dollar",
    TJS: "TJ-Tajikistani Somoni",
    TRY: "TR-Turkish lira",
    UAH: "UA-Ukrainian hryvnia",
    UGX: "UG-Ugandan Shilling ",
    USD: "US-United States Dollar",
    UYU: "UY-Uruguayan peso",
    UZS: "UZ-Uzbekistani Som",
    YER: "YE-Yemeni Rial",
    ZAR: "ZA-South African Rand",
    ZMK: "ZM-Zambian Kwacha",
  };